pyproject.toml
tests/unit_tests/test_compile.py
tests/unit_tests/test_vectorstore.py

Fix import in unit tests

---

.github/workflows/ci.yml
pyproject.toml
tests/unit_tests/test_vectorstore.py
tests/utils.py

bump timeout

---

.github/workflows/_release.yml
.github/workflows/release.yml

Add release workflow

---

langchain_postgres/vectorstores.py
tests/unit_tests/test_vectorstore.py

Update embeddings_function -> embeddings

---

.github/workflows/_test.yml
.github/workflows/ci.yml
langchain_postgres/vectorstores.py
tests/unit_tests/test_vectorstore.py

Update session management in vectorstore

---

langchain_postgres/vectorstores.py
tests/unit_tests/fixtures/filtering_test_cases.py

So... yeah I f***ed up. But this is the fix.
The $exists was working as the $null, but the rename implies also changing how the bool value is interpreted:
$exists: True (there is a tag, I don't care the value)
$exists: False (no tag in there)
ref: https://github.com/langchain-ai/langchain-postgres/pull/40

vectorstore: Fix in exists operator. Was working as null

---

pyproject.toml

The  "Source Code" param was missing in the pyproject.toml. It is used to generate the package list in the LangChain [documentation](https://langchain-3amlg0zta-langchain.vercel.app/v0.2/docs/integrations/platforms/)

Add URL to source code to pyproject.toml

---

langchain_postgres/vectorstores.py

Document filters in the doc-string for pgvectorstore

pgvector document filters

---

langchain_postgres/vectorstores.py
tests/unit_tests/fixtures/filtering_test_cases.py

Add unit tests for $in and $nin operators

add unit tests for $in and $nin operators

---

langchain_postgres/vectorstores.py
tests/unit_tests/fixtures/filtering_test_cases.py
tests/unit_tests/test_vectorstore.py

Add support for the Negation(`$not`) operator in PGVector

Add support for the Negation('$not') operator

---

langchain_postgres/__init__.py
langchain_postgres/translator.py
tests/unit_tests/query_constructors/test_pgvector.py
tests/unit_tests/test_imports.py

The `SelfQuery PGVectorTranslator` is not correct. The operator is "eq" and not "$eq".
This patch implements a new version of `PGVectorTranslator`.
It's necessary to release a new version before accepting [another PR](https://github.com/langchain-ai/langchain/pull/23217) in langchain core.

Add transalor

---

langchain_postgres/vectorstores.py
poetry.lock
pyproject.toml
tests/unit_tests/test_vectorstore.py
tests/unit_tests/test_vectorstore_standard_tests.py

* Add support for standard get_by_ids, aget_by_ids
* Add support for upsert and aupsert
* Remove add_texts and aadd_texts

Implementation of upsert, aupsert, get_by_ids, aget_by_ids

---

langchain_postgres/vectorstores.py
poetry.lock
pyproject.toml

* this change has not been released yet.
* add_documents and add_texts can be used instead of the upsert method. The semantics for those methods ARE upsert semantics when an ID is provided!

patch: revert unreleased upsert change

---

CONTRIBUTING.md
DEVELOPMENT.md

As suggested by @Sachin-Bhat per GH-92.

Documentation: Add CONTRIBUTING.md and DEVELOPMENT.md

---

poetry.lock
pyproject.toml

All async tests apparently need it. Otherwise:
```shell
pytest -vvv -k test_async_pgvector
```
```python
ValueError: the greenlet library is required to use this function. No module named 'greenlet'
```

Dependencies: Add `greenlet` package to `test` dependency group

---

README.md

Update the repo README to note Google provided integrations

docs: update the readme to note Google provided integrations

---

langchain_postgres/chat_message_histories.py

Fixes mypy error:
langchain_postgres/chat_message_histories.py:344: error: Cannot override writeable attribute with read-only property  [override] Found 1 error in 1 file (checked 37 source files)

fix: Add setter for Chat Message History messages

---

README.md
langchain_postgres/vectorstores.py

I've decided to keep the Google Cloud Integrations section at the bottom. I will send separate PRs for the migration script and quickstart update.

docs: refactor the readme

---

examples/pg_vectorstore.ipynb
langchain_postgres/chat_message_histories.py

chore: Update PGVectorstore quickstart
Changes:
- The instances where the variable `engine` is being used instead of `pg_engine`
- Added Cohere embedding model along with the right vector size for the model
- Change to use `embedding` parameter instead of `embedding_service` in vectorstore.afrom_documents
Fixes #180

chore: Update PGVectorstore quickstart

---

examples/pg_vectorstore.ipynb

current example w/ ID field wasn't working perhaps due to a collision in the metadata fields and the ID column

docs: update tutorial

---

langchain_postgres/v2/async_vectorstore.py

chore: Update vectorstore search to support inline embedding
While using inline embedding functions in the current select sql query, due to parameterization, sql throws an error( The parameter has to already be in vector datatype). 
This change is to support inline embedding functions.

chore: Update vectorstore search to support inline embedding

---

langchain_postgres/v2/async_vectorstore.py
tests/unit_tests/fixtures/metadata_filtering_data.py

Fixed issue #216. 
Pull request adds a filter test case that was failing and the fix for internal function _handle_field_filter. 
The function fix is to add an unique identifier to the column names of operator in, nin, like and ilike

Fixed support for VectorStore search filters with multiple $like/$ilike/$in/$nin on same column

---

README.md
examples/pg_vectorstore_how_to.ipynb

Adds documentation for hybrid search
This PR adds:
- A code snippet in the README
- Section in the how-to guide on multiple scenarios the hybrid search config can be used in. The scenarios are
- Creating a new table with the tsv column
- Using a pre-existing table without the tsv column
- Hybrid search only on specific similarity searches.
- Applying hybrid search index

docs: Add documentation for Hybrid Search

---

examples/pg_vectorstore_how_to.ipynb

This PR adds a clarification into the PGVectorStore How-To guide that the dense vector search is the primary search and the TSV based search is the secondary search.

chore: update PGVectorStore How to guide
